#include "../flipper/core/rid.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
static RidPacket basic(void) {
    /* Fixed F3411/OpenDroneID v2 Basic ID vector, not generated by our encoder. */
    RidPacket p = {
        .transport = 1, .mac = {2, 3, 4, 5, 6, 7}, .rssi = -42, .channel = 6, .length = 25};
    p.payload[0] = 0x02;
    p.payload[1] = 0x12;
    memcpy(p.payload + 2, "DRONERID-TEST-000001", 20);
    return p;
}
static void framing(void) {
    RidStream s = {0};
    RidPacket p = basic(), q;
    char line[RID_MAX_LINE];
    size_t n = rid_wire_packet(&p, line, sizeof(line));
    assert(n && n < sizeof(line));
    int result = 0;
    for(size_t i = 0; i < n; i++)
        result = rid_stream_byte(&s, line[i], &q);
    assert(result == 1 && q.length == 25 && q.rssi == -42 && !memcmp(q.payload, p.payload, 25));
    line[30] = line[30] == 'A' ? 'B' : 'A';
    for(size_t i = 0; i < n; i++)
        assert(rid_stream_byte(&s, line[i], &q) == 0);
    assert(s.bad == 1);
    for(int i = 0; i < 1000; i++)
        rid_stream_byte(&s, 'X', &q);
    rid_stream_byte(&s, '\n', &q);
    assert(s.bad == 2);
    n = rid_wire_heartbeat(line, sizeof(line));
    for(size_t i = 0; i < n; i++)
        result = rid_stream_byte(&s, line[i], &q);
    assert(result == 2);
    assert(!rid_wire_packet(&p, line, 2));
    p.length = RID_MAX_PAYLOAD;
    n = rid_wire_packet(&p, line, sizeof(line));
    assert(n);
    for(size_t i = 0; i < n; i++)
        result = rid_stream_byte(&s, line[i], &q);
    assert(result == 1 && q.length == RID_MAX_PAYLOAD);
}
static void decoding(void) {
    RidStore s = {0};
    RidPacket p = basic();
    assert(rid_ingest(&s, &p, 100));
    assert(s.tracks[0].uas.BasicIDValid[0]);
    assert(!strcmp(s.tracks[0].uas.BasicID[0].UASID, "DRONERID-TEST-000001"));
    for(int n = 0; n < 25; n++) {
        p.length = n;
        assert(!rid_ingest(&s, &p, 101));
    }
    p = basic();
    RidPacket pack = p;
    pack.length = 53;
    pack.payload[0] = 0xf2;
    pack.payload[1] = 25;
    pack.payload[2] = 2;
    memcpy(pack.payload + 3, p.payload, 25);
    ODID_Location_data loc;
    odid_initLocationData(&loc);
    loc.Latitude = 40.5;
    loc.Longitude = -73.25;
    loc.AltitudeGeo = 120;
    ODID_Location_encoded enc;
    assert(encodeLocationMessage(&enc, &loc) == ODID_SUCCESS);
    memcpy(pack.payload + 28, &enc, 25);
    assert(rid_ingest(&s, &pack, 200));
    assert(fabs(s.tracks[0].uas.Location.Latitude - 40.5) < 1e-6);
    assert(s.tracks[0].field_ms[1] == 200);
    assert(rid_ingest(&s, &p, 300));
    assert(s.tracks[0].field_ms[1] == 200);
    RidStore before = s;
    pack.payload[28] = 0xf2;
    assert(!rid_ingest(&s, &pack, 400));
    assert(!memcmp(s.tracks, before.tracks, sizeof(s.tracks)));
    pack.payload[28] = 0x12;
    pack.payload[2] = 255;
    assert(!rid_ingest(&s, &pack, 400));
    p.payload[0] = 0x09;
    assert(!rid_ingest(&s, &p, 400));
    p = basic();
    p.transport = 2;
    assert(rid_ingest(&s, &p, 400));
    assert(s.tracks[1].used); /* same MAC, different transport: no unsafe merge */
    memset(&s, 0, sizeof(s));
    p = basic();
    for(int i = 0; i < 20; i++) {
        p.mac[5] = i;
        assert(rid_ingest(&s, &p, i));
    }
    assert(s.evicted == 12);
    memset(&s, 0, sizeof(s));
    p = basic();
    assert(rid_ingest(&s, &p, UINT32_MAX - 50));
    assert((uint32_t)(10 - s.tracks[0].seen_ms) == 61);
}
static void more_messages(void) {
    RidStore s = {0};
    RidPacket p = basic();
    assert(rid_ingest(&s, &p, 100));
    ODID_Location_data loc;
    odid_initLocationData(&loc);
    loc.Latitude = 10;
    loc.Longitude = 20;
    ODID_Location_encoded location;
    assert(encodeLocationMessage(&location, &loc) == ODID_SUCCESS);
    memcpy(p.payload, &location, 25);
    assert(rid_ingest(&s, &p, 200));
    p = basic();
    p.payload[2] = 'X';
    assert(rid_ingest(&s, &p, 300));
    assert(!s.tracks[0].uas.LocationValid);
    ODID_System_data sys;
    odid_initSystemData(&sys);
    sys.OperatorLatitude = 30;
    sys.OperatorLongitude = -40;
    ODID_System_encoded system;
    assert(encodeSystemMessage(&system, &sys) == ODID_SUCCESS);
    memcpy(p.payload, &system, 25);
    assert(rid_ingest(&s, &p, 400));
    assert(s.tracks[0].uas.SystemValid);
    assert(fabs(s.tracks[0].uas.System.OperatorLatitude - 30) < 1e-6);
    ODID_SelfID_data self;
    odid_initSelfIDData(&self);
    strcpy(self.Desc, "Synthetic test");
    ODID_SelfID_encoded self_enc;
    assert(encodeSelfIDMessage(&self_enc, &self) == ODID_SUCCESS);
    memcpy(p.payload, &self_enc, 25);
    assert(rid_ingest(&s, &p, 500));
    assert(s.tracks[0].uas.SelfIDValid);
    ODID_OperatorID_data op;
    odid_initOperatorIDData(&op);
    strcpy(op.OperatorId, "TESTOPERATOR");
    ODID_OperatorID_encoded op_enc;
    assert(encodeOperatorIDMessage(&op_enc, &op) == ODID_SUCCESS);
    memcpy(p.payload, &op_enc, 25);
    assert(rid_ingest(&s, &p, 600));
    assert(s.tracks[0].uas.OperatorIDValid);
    ODID_Auth_data auth;
    odid_initAuthData(&auth);
    auth.DataPage = 15;
    ODID_Auth_encoded auth_enc;
    assert(encodeAuthMessage(&auth_enc, &auth) == ODID_SUCCESS);
    memcpy(p.payload, &auth_enc, 25);
    assert(rid_ingest(&s, &p, 700));
    assert(s.tracks[0].uas.AuthValid[15]);
    RidStore before = s;
    location.Latitude = INT32_MAX;
    memcpy(p.payload, &location, 25);
    assert(!rid_ingest(&s, &p, 800));
    assert(!memcmp(s.tracks, before.tracks, sizeof(s.tracks)));
    p.length = 53;
    p.payload[0] = 0xf2;
    p.payload[1] = 25;
    p.payload[2] = 2;
    memcpy(p.payload + 3, &system, 25);
    memcpy(p.payload + 28, &system, 25);
    assert(!rid_ingest(&s, &p, 900));
}
static void adapters(void) {
    RidPacket p = basic(), q;
    uint8_t f[100] = {0x80};
    memcpy(f + 10, p.mac, 6);
    f[36] = 221;
    f[37] = 30;
    memcpy(f + 38, "\xFA\x0B\xBC\x0D", 4);
    f[42] = 9;
    memcpy(f + 43, p.payload, 25);
    assert(rid_beacon(f, 68, -42, 6, &q));
    assert(!memcmp(q.payload, p.payload, 25));
    for(size_t n = 0; n < 68; n++)
        assert(!rid_beacon(f, n, -42, 6, &q));
    f[37] = 255;
    assert(!rid_beacon(f, 68, -42, 6, &q));
    f[37] = 30;
    f[38] = 0;
    assert(!rid_beacon(f, 68, -42, 6, &q));
    uint8_t ad[31] = {30, 0x16, 0xfa, 0xff, 0x0d, 9};
    memcpy(ad + 6, p.payload, 25);
    assert(rid_ble_ad(ad, sizeof(ad), p.mac, -50, &q));
    assert(q.transport == 2 && q.length == 25);
    for(size_t n = 0; n < 31; n++)
        assert(!rid_ble_ad(ad, n, p.mac, -50, &q));
}
static void fuzz_smoke(void) {
    RidStore s = {0};
    RidStream stream = {0};
    RidPacket p = {0}, q;
    uint8_t bytes[512];
    srand(42);
    for(unsigned i = 0; i < 100000; i++) {
        size_t n = rand() % sizeof(bytes);
        for(size_t j = 0; j < n; j++)
            bytes[j] = rand();
        rid_beacon(bytes, n, -30, 6, &p);
        rid_ble_ad(bytes, n, bytes, -30, &p);
        p.length = rand() % (RID_MAX_PAYLOAD + 10);
        p.transport = 1;
        memcpy(p.payload, bytes, sizeof(p.payload));
        rid_ingest(&s, &p, i);
        for(size_t j = 0; j < n; j++)
            rid_stream_byte(&stream, bytes[j], &q);
    }
}
int main(int argc, char** argv) {
    framing();
    decoding();
    more_messages();
    adapters();
    fuzz_smoke();
    if(argc > 1) {
        FILE* f = fopen(argv[1], "wb");
        assert(f);
        RidPacket p = basic();
        char line[RID_MAX_LINE];
        size_t n = rid_wire_packet(&p, line, sizeof(line));
        assert(fwrite(line, 1, n, f) == n);
        fclose(f);
    }
    puts(
        "PASS: framing, CRC, truncation, decode, packs, staleness, eviction, adapters, 100000 random cases");
    return 0;
}
